### ISSUE TITLE
[exporter-prometheus] repl.js raises an error `Invalid metric name`

### ISSUE THREAD

**Issue by isaikevych** [census-instrumentation/opencensus-node#165]
LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR
/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/prom-client/lib/counter.js:62
			throw new Error('Invalid metric name');
			^

Error: Invalid metric name
    at new Counter (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/prom-client/lib/counter.js:62:10)
    at PrometheusStatsExporter.registerMetric (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/@opencensus/exporter-prometheus/build/src/prometheus-stats.js:74:26)
    at PrometheusStatsExporter.updateMetric (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/@opencensus/exporter-prometheus/build/src/prometheus-stats.js:102:29)
    at PrometheusStatsExporter.onRecord (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/@opencensus/exporter-prometheus/build/src/prometheus-stats.js:49:18)
    at Stats.record (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/node_modules/@opencensus/core/build/src/stats/stats.js:107:26)
    at Interface.<anonymous> (/Users/prakritibansal/Desktop/Fifth Semester/OpenCensus/node-app-2/repl.js:77:9)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)

**Comment by songy23** [comment]
FYI, in Prometheus there're some [restrictions on the metric names](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels):
> It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.

So if the metric name contains '/' or other unsupported characters, you'll get this kind of error.

In Java and Go we do sanitization on metric names: https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/prometheus/prometheus.go#L260.

**Comment by songy23** [comment]
Filed https://github.com/census-instrumentation/opencensus-node/issues/167 to follow up. Closing this issue.
