### ISSUE TITLE
Tests fail on a fresh repo clone

### ISSUE THREAD

**Issue by ofrobots** [census-instrumentation/opencensus-node#37]
After a fresh repo clone, I see lots of test failures.

```sh
...
...
...
> @opencensus/exporter-zipkin@0.0.1 posttest /Users/ofrobots/src/opencensus/opencensus-node/packages/opencensus-exporter-zipkin
> npm run check


> @opencensus/exporter-zipkin@0.0.1 check /Users/ofrobots/src/opencensus/opencensus-node/packages/opencensus-exporter-zipkin
> gts check

lerna ERR! test Errored while running script in '@opencensus/exporter-stackdriver'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 3
lerna ERR! npm ERR! @opencensus/exporter-stackdriver@0.0.1 test: `nyc -x '**/test/**' --reporter=html --reporter=text mocha 'build/test/**/*.js'`
lerna ERR! npm ERR! Exit status 3
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @opencensus/exporter-stackdriver@0.0.1 test script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/ofrobots/.npm/_logs/2018-06-12T03_47_42_203Z-debug.log
lerna ERR!
lerna ERR! > @opencensus/exporter-stackdriver@0.0.1 pretest /Users/ofrobots/src/opencensus/opencensus-node/packages/opencensus-exporter-stackdriver
lerna ERR! > npm run compile; cp -r ./test/fixtures ./build/test/
lerna ERR!
lerna ERR!
lerna ERR! > @opencensus/exporter-stackdriver@0.0.1 compile /Users/ofrobots/src/opencensus/opencensus-node/packages/opencensus-exporter-stackdriver
lerna ERR! > tsc -p .
lerna ERR!
lerna ERR!
lerna ERR! > @opencensus/exporter-stackdriver@0.0.1 test /Users/ofrobots/src/opencensus/opencensus-node/packages/opencensus-exporter-stackdriver
lerna ERR! > nyc -x '**/test/**' --reporter=html --reporter=text mocha 'build/test/**/*.js'
...
...
...
```

**Comment by kjin** [comment]
@fabiogomessilva This still applies. I am seeing SD Exporter failures on my local machine. Maybe an env var problem?

```
1) Stackdriver Exporter
       publish()
         should fail exporting by authentication error:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at exporter.publish.then (build/test/test-stackdriver.js:107:28)
      at propagateAslWrapper (/Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:502:23)
      at /Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:539:70
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Stackdriver Exporter
       publish()
         should export traces to stackdriver:
     TypeError: result.indexOf is not a function
      at exporter.publish.then (build/test/test-stackdriver.js:148:38)
      at propagateAslWrapper (/Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:502:23)
      at /Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:539:70
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) Stackdriver Exporter
       publish()
         should fail exporting by network error:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at exporter.publish.then (build/test/test-stackdriver.js:163:28)
      at propagateAslWrapper (/Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:502:23)
      at /Users/kjin/Documents/oc-node-2/packages/opencensus-core/node_modules/async-listener/index.js:539:70
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kjin** [comment]
@fabiogomessilva Issues seem related to env vars on my local machine. Things worked after I ran it in a docker container.
