### ISSUE TITLE
Opencensus/instrumentation-http http.js hostname undefined

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-node#416]
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
0.0.9

### What version of Node are you using?
v.10.13.0

### What did you do?
used instrumentation-http plugin for tracing

### What did you see instead?
```shell
(node:56170) UnhandledPromiseRejectionWarning: Error: Unsupported type : undefined
    at createAttributeValue (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace-utils.js:134:19)
    at createAttributesBuilder (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace-utils.js:113:29)
    at Object.createAttributes (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace-utils.js:49:31)
    at StackdriverTraceExporter.createSpan (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace.js:95:56)
    at rootSpans.forEach.rootSpan (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace.js:78:36)
    at Array.forEach (<anonymous>)
    at StackdriverTraceExporter.<anonymous> (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace.js:76:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/@opencensus/exporter-stackdriver/build/src/stackdriver-cloudtrace.js:19:58)
    at propagateAslWrapper (/Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/async-listener/index.js:504:23)
    at /Users/jinsuk/Code/w4/chatbots/service/backoffice/node_modules/async-listener/index.js:541:70
(node:56170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by mayurkale22** [comment]
Thanks for filling the issue, I have added a comment on your fix. PTAL
